sudo: required
services:
  - docker
before_install:
  - docker build -t amalesa/multi-docker-test -f Dockerfile.dev ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true amalesa/multi-docker-test npm run test -- --
after_success:
  - docker build -t amalesa/multi-client ./client






