sudo: required
services:
  - docker

before_install:
  - docker build -t amalesa/multi-docker-test -f ./client/Dockerfile.dev

  script:
  - docker run -e CI=true amalesa/multi-docker-test npm run test -- --coverage



