  
sudo: required
services:
  - docker
before_install:
  - docker build -t amalesa/multi-docker-client-test -f ./client/Dockerfile.dev ./client
script:
  - docker run amalesa/multi-docker-client-test npm test -- --coverage
after_success:
  - docker build -t amalesa/multi-client ./client
  - docker build -t amalesa/multi-nginx ./nginx
  - docker build -t amalesa/multi-server ./server
  - docker build -t amalesa/multi-worker ./worker

- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

- docker push amalesa/multi-client
- docker push amalesa/multi-nginx
- docker push amalesa/multi-server
- docker push amalesa/multi-worker
